### ISSUE TITLE
Installation fails.

### ISSUE THREAD

**Issue by s-ota-66** [aaryankotharii/ShazamKit-Demo#3]
Cannot install for the reason that info.plist is missing.

error: Build input file cannot be found: '/Users/dev/Xcode/Examples/ShazamKit-Demo/Application/ShazamKit-Demo/Info.plist' (in target 'ShazamKit-Demo' from project 'ShazamKit-Demo')

**Comment by aaryankotharii** [comment]
Hi @s-ota-66, This is a bug for SwiftUI apps in Xcode 13.
Please follow option 1 of [this article](https://betterprogramming.pub/info-plist-is-missing-in-xcode-13-heres-how-to-get-it-back-1a7abf3e2514) to retrieve the property list.

**Comment by s-ota-66** [comment]
Thank you!
I was able to launch the application.
Thanks for the great program!
